name: Unit test
on: [push, pull_request]
jobs:
  build:
    name: Build application
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: 12.x-${{ runner.OS }}-build-${{ hashFiles('package.json') }}

      - name: Run npm build
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: npm install

      - name: Run npm build
        run: npm build
